DROP TABLE users CASCADE;
DROP TABLE restaurants CASCADE;
DROP TABLE tables CASCADE;
DROP TABLE menus CASCADE;
DROP TABLE menuCourses CASCADE;
DROP TABLE menuItems CASCADE;
DROP TABLE reservations CASCADE;
DROP TABLE reviews CASCADE;
